---
title: "Close-Elections-Female"
author: "Vandrade"
date: "2025-03-16"
output: html_document
---

# Bibliotecas
```{r}
library(tidyverse)
library(rdrobust)
library(readr)
library(microdatasus)
# library(gt)
# library(gtsummary)

```

# DATASUS

```{r}

datasus_raw <- fetch_datasus(year_start = 2005, year_end = 2024, uf = "all", information_system = "SIM-DOEXT")

datasus_geral_tratado <- datasus_raw |>

  select(cid_causa_bas = CAUSABAS,
         cid_linha_aa = LINHAA,
         cid_linha_ab = LINHAB,
         cid_linha_ac = LINHAC,
         cid_linha_ad = LINHAD,
         cd_sexo = SEXO, # 0-Ignorado, 1-Masculino, 2-Feminino
         cd_raca = RACACOR, # 1-Branca, 2-Preta, 3-Amarela, 4-Parda, 5-Indígena
         cd_estado_civil = ESTCIV, # 1-Solteiro, 2-Casado, 3-Viúvo, 4-Separado judicialmente, 5-União consensual (versões anteriores) 9-Ignorado
         dt_obito = DTOBITO, # dd/mm/aaaa
         dt_nasc = DTNASC,  # dd/mm/aaaa
         cd_escolaridade = ESC, # 1-Nenhuma, 2-1 a 3 anos, 3-4 a 7 anos, 4-8 a 11 anos, 5-12 e mais, 9-Ignorado
         ocup_cbo = OCUP, #CBO2002
         cd_muni_res = CODMUNRES, # IBGE
         cd_local_ocor = LOCOCOR, # 9-Ignorado, 1-Hospital, 2-Outro estab saúde, 3-Domicílio, 4-Via Pública 5-Outros
         cd_muni_ocor = CODMUNOCOR, # IBGE
         tipo_acidente = CIRCOBITO # 9-Ignorado, 1-Acidente, 2-Suicídio, 3-Homicídio, 4-Outros
         ) |>

  mutate(cd_muni_res = as.factor(substr(cd_muni_res, 1, 6)),
         cd_muni_ocor = as.factor(substr(cd_muni_ocor, 1, 6)),
         dt_obito = as.Date(dt_obito, format="%d%m%Y"),
         ano_obito = year(dt_obito),
         dt_nasc = as.Date(dt_nasc, format="%d%m%Y"),
         idade = as.integer(difftime(dt_obito, dt_nasc, units = "days") / 365.25),

         mandato = case_when(ano_obito %% 4 == 0 ~ ano_obito - 4,
                             ano_obito %% 4 == 1 ~ ano_obito - 1,
                             ano_obito %% 4 == 2 ~ ano_obito - 2,
                             ano_obito %% 4 == 3 ~ ano_obito - 3)) |>
  mutate(
    cid_linha_aa = str_split(cid_linha_aa, "\\*") |> map(~ .x[.x != ""]),
    cid_linha_ab = str_split(cid_linha_ab, "\\*") |> map(~ .x[.x != ""]),
    cid_linha_ac = str_split(cid_linha_ac, "\\*") |> map(~ .x[.x != ""]),
    cid_linha_ad = str_split(cid_linha_ad, "\\*") |> map(~ .x[.x != ""])) |>
  mutate(
    cid10_direct_and_antecedents = pmap(list(basica = cid_causa_bas, a = cid_linha_aa, b = cid_linha_ab, c = cid_linha_ac, d = cid_linha_ad),
                                        function(basica, a, b, c, d) c(basica, a, b, c, d))) |>

  select(-cid_linha_aa, -cid_linha_ab, -cid_linha_ac, -cid_linha_ad) |>

  mutate(visual_lista = map_chr(cid10_direct_and_antecedents, ~ paste(., collapse = ", ")))

datasus_geral_tratado |> write_rds("../../dados/Datasus/SIMSUS/datasus_geral_tratado.rds")

datasus_geral_tratado <- readRDS("../../dados/Datasus/SIMSUS/datasus_geral_tratado.rds")

```

# criando lista de CIDS

```{r}
cid10_verificador <- function(coluna, cid_inicio, cid_fim) {
  # Verifica se é lista
  if (is.list(coluna)) {
    map_lgl(
      coluna,
      ~ {
        cids_validos <- .x[!is.na(.x)]
        any(substr(cids_validos, 1, 3) >= cid_inicio & substr(cids_validos, 1, 3) <= cid_fim)
      }
    )
  } else {
    # vetor simples
    cids_validos <- ifelse(is.na(coluna), NA_character_, substr(coluna, 1, 3))
    cids_validos >= cid_inicio & cids_validos <= cid_fim
  }
}
```


## Homicidio e Feminicidio
```{r}

var_dependentes_simsus <- datasus_geral_tratado |>
  mutate(
    # 1. Suicídio (X60–X84 e Y87)
    y_suicide = cid10_verificador(cid10_direct_and_antecedents, "X60", "X84") |
                cid10_verificador(cid10_direct_and_antecedents, "Y87", "Y87"),
    
    # 2. Overdose (X40–X45, Y10–Y15, Y45, Y47, Y49)
    y_overdose = cid10_verificador(cid10_direct_and_antecedents, "X40", "X45") |
                 cid10_verificador(cid10_direct_and_antecedents, "Y10", "Y15") |
                 cid10_verificador(cid10_direct_and_antecedents, "Y45", "Y45") |
                 cid10_verificador(cid10_direct_and_antecedents, "Y47", "Y47") |
                 cid10_verificador(cid10_direct_and_antecedents, "Y49", "Y49"),
    
    # 3. Doença hepática alcoólica (K70–K74)
    y_alcoholic_disease = cid10_verificador(cid10_direct_and_antecedents, "K70", "K74"),
    
    # 4. Homicídio doméstico (X85–Y09) + local = domicílio
    y_domestic_homicide = cid10_verificador(cid10_direct_and_antecedents, "X85", "Y09") &
                          cd_local_ocor == "3")




var_dependentes_simsus |> write_rds("../../dados/Datasus/SIMSUS/var_dependentes_simsus.RDS")
```



# TSE
```{r}

candidatos <- readRDS("../dados/TSE/candidates-att.rds")

prefeitos <- candidatos |> 
  
  group_by(ano, estado, cd_municipio_tse) |> 
  arrange(desc(total_votos)) |> 
  slice_head(n = 2) |> 
  filter(!is.na(genero)) |> 
  group_by(ano, estado, cd_municipio_tse) |> 
  
  filter(n_distinct(genero) == 2) |> 
  
  mutate(mg_fem = (total_votos[genero == 'FEMININO'] - total_votos[genero == 'MASCULINO'])/sum(total_votos),
         eleita = ifelse(mg_fem > 0, TRUE, FALSE),
         pop_total = pop_mas + pop_fem,
         educacao_agr = case_when(educacao %in% c('1º GRAU COMPLETO', '1º GRAU INCOMPLETO', 'ENSINO FUNDAMENTAL COMPLETO', 'ENSINO FUNDAMENTAL INCOMPLETO', 'FUNDAMENTAL COMPLETO', 'FUNDAMENTAL INCOMPLETO', 'ANALFABETO', 'LÊ E ESCREVE') ~ 'fundamental',
           educacao %in% c('2º GRAU COMPLETO', '2º GRAU INCOMPLETO', 'ENSINO MÉDIO COMPLETO', 'ENSINO MÉDIO INCOMPLETO', 'MÉDIO COMPLETO', 'MÉDIO INCOMPLETO') ~ 'medio',
           educacao %in% c('SUPERIOR COMPLETO', 'SUPERIOR INCOMPLETO') ~ 'superior',
           TRUE ~ NA_character_),
         
         codigo_ibge = as.factor(codigo_ibge),
         codigo_ibge_sus = as.character(codigo_ibge_sus)) |> 

  filter(resultado == 'Eleito', pop_votante <= 200000) |> 
  ungroup()


```

# JOIN
```{r}

df_prefeitos_simsus <- prefeitos |> 
  left_join(datasus_homicide, by = c('ano' = 'mandato', 'codigo_ibge_sus' = 'cd_muni_res')) |> 
  
  mutate(codigo_ibge = as.factor(codigo_ibge),
         across(starts_with('y_'), ~ (./pop_total)*100000),
         across(starts_with('y_'), ~ replace_na(., 0)),
         ano = as.factor(ano),
         educacao_agr = as.factor(educacao_agr),
         partido = as.factor(partido)) |> 
  
  filter(!ano %in% c(2000, 2016, 2020),
         !codigo_ibge_sus %in% c("150475", "270440", "120045", "210220", "316960", "251065"))

```


# RDD

## RD Plots
```{r}

rdplot(df_prefeitos_simsus$y_domestic_homicide, df_prefeitos_simsus$mg_fem, kernel = "triangular", x.lim = c(-.20, .20), y.lim = c(0, 5), nbins = 100, p = 1)

rdplot(df_prefeitos_simsus$y_domestic_homicide_t_1, df_prefeitos_simsus$mg_fem, kernel = "triangular", x.lim = c(-.20, .20), y.lim = c(0, 5), nbins = 100, p = 3)

```


## Regressao
```{r}

controls <- model.matrix(~ ano + partido + idade + educacao_agr + prop_fem_pop + pop_total, data = df_prefeitos_simsus)

teste <- rdrobust(x = df_prefeitos_simsus$mg_fem,
         y = df_prefeitos_simsus$y_domestic_homicide,
         covs = controls, 
         cluster = df_prefeitos_simsus$codigo_ibge, 
         all = TRUE, 
         kernel = "triangular") 

```

## Montando função RDD

```{r}



RDD <- function(x, y) {
  
  controls <- model.matrix(~ ano + partido + idade + educacao_agr + prop_fem_pop + pop_total, data = df_prefeitos_simsus)
  
  regressao <- rdrobust(x = x,
           y = y,
           covs = controls,
           cluster = df_prefeitos_simsus$codigo_ibge,
           all = TRUE,
           kernel = "triangular")
  
  regressao |> summary() |> print()

  h <- regressao$bws[1]


  x_vals <- x[abs(x) <= h]
  y_vals <- y[abs(x) <= h]
  
  
  dados_filtrados <- tibble(x = x, y = y) |>
    filter(abs(x) <= h)

  ymax <- mean(dados_filtrados$y)

  
  rdplot(y = y, x = x,
         kernel = "triangular",
         x.lim = c(-h, h),
         y.lim = c(0, ymax + 3),   
         nbins = 100,
         p = 1)
  }
```


```{r}

RDD(df_prefeitos_simsus$mg_fem, df_prefeitos_simsus$y_domestic_homicide)

```



# Robustez

```{r}

controls <- model.matrix(~ ano + partido + idade + educacao_agr + prop_fem_pop + pop_total, data = df_prefeitos_simsus)

bandwidths <- seq(0.05, 1, by = 0.05)

betas <- numeric(length(bandwidths))
pvalues <- numeric(length(bandwidths))

for (i in seq_along(bandwidths)) {
  
  h <- bandwidths[i]
  
  rd_robust_result <- rdrobust(x = df_prefeitos_simsus$mg_fem,
         y = df_prefeitos_simsus$y_domestic_homicide,
         covs = controls, 
         cluster = df_prefeitos_simsus$codigo_ibge, 
         h = h,
         all = TRUE, 
         kernel = "triangular") 
  
  betas[i] <- rd_robust_result$coef[1]
  pvalues[i] <- rd_robust_result$pv[1]

}    


results <- data.frame(
  bandwidth = bandwidths,
  beta = betas,
  pvalue = pvalues)

results |> 
  pivot_longer(beta:pvalue) |> 
  ggplot(aes(x=bandwidth, y = value)) + 
  geom_line() + 
  facet_grid(rows = vars(name), scales = "free_y") 
```


```{r}
RDD(df_prefeitos_simsus$mg_fem, df_prefeitos_simsus$y_domestic_homicide)

```

```{r}
df_prefeitos_simsus

```



