---
title: "rdd_base_consolidada"
output: html_document
date: "2025-08-28"
---

#Bibliotecas
```{r}
library(tidyverse)
library(haven)
library(purrr)
library(rlang)
```
## Bases raw
```{r}
df_adriano_raw <- read_dta('../../dados/Bases/Base_cosolidada_TCC_base3.dta')

df_adriano_raw |> view()
```

```{r}
df_candidates <- readRDS('../../dados/TSE_tratado_completo.RDS')
```


#Base RDD
saude mental: soma das qtd eq xx
```{r}
df_adriano <- df_adriano_raw |> 
  select(cd_muni_ibge = ibge, year, beneficio_medi_tot, qt_equipes_sf, 
         acsimplantado, nasf_acum, unidades_caps, qtd_equipes58, qtd_equipes59, qtd_equipes60, qtd_equipes75, saude_mental) |> 
  mutate(
    mandato = case_when(year %% 4 == 0 ~ year - 4,
                        year %% 4 == 1 ~ year - 1,
                        year %% 4 == 2 ~ year - 2,
                        year %% 4 == 3 ~ year - 3),
    cd_muni_ibge = as.character(cd_muni_ibge),
    across(where(is.numeric), ~ ifelse(is.nan(.), NA, .))
  ) |> 
  group_by(cd_muni_ibge, mandato) |> 
  summarise(
    total_beneficio_medi_tot = sum(beneficio_medi_tot, na.rm = TRUE),
    total_qt_equipes_sf      = sum(qt_equipes_sf, na.rm = TRUE),
    total_acsimplantado      = sum(acsimplantado, na.rm = TRUE),
    total_unidades_caps      = sum(unidades_caps, na.rm = TRUE),
    total_nasf               = sum(nasf_acum, na.rm=TRUE),
    total_qtd_equipes58      = sum(qtd_equipes58, na.rm=TRUE),
    total_qtd_equipes59      = sum(qtd_equipes59, na.rm=TRUE),
    total_qtd_equipes60      = sum(qtd_equipes60, na.rm=TRUE),
    total_qtd_equipes75      = sum(qtd_equipes75, na.rm=TRUE),
    total_saude_mental       = sum(saude_mental, na.rm=TRUE),
    .groups = "drop"
  ) |> 
  arrange(cd_muni_ibge, mandato) |> 
  group_by(cd_muni_ibge) |> 
  mutate(
    y_beneficio_medi_tot = total_beneficio_medi_tot - lag(total_beneficio_medi_tot),
    y_qt_equipes_sf      = total_qt_equipes_sf      - lag(total_qt_equipes_sf),
    y_acsimplantado      = total_acsimplantado      - lag(total_acsimplantado),
    y_unidades_caps      = total_unidades_caps      - lag(total_unidades_caps),
    y_nasf               = total_nasf      - lag(total_nasf),
    y_qtd_equipes58      = total_qtd_equipes58      - lag(total_qtd_equipes58),
    y_qtd_equipes59      = total_qtd_equipes59      - lag(total_qtd_equipes59),
    y_qtd_equipes60      = total_qtd_equipes60      - lag(total_qtd_equipes60),
    y_qtd_equipes75      = total_qtd_equipes75      - lag(total_qtd_equipes75),
    y_saude_mental       = total_saude_mental      - lag(total_saude_mental),
  )
```



```{r}

df_rdd_adriano <- df_candidates |>
  filter(!ano %in% c('2004')) |> 
  left_join(df_adriano, by = c('ano' = 'mandato', 'cd_municipio_ibge_6' = 'cd_muni_ibge')) |> 
  
  mutate(y_beneficio_medi_tot = (y_beneficio_medi_tot/cov_municipio_pop_total)*10000,
         y_nasf = (y_nasf/cov_municipio_pop_total)*10000,
         y_qtd_equipes58  = (y_qtd_equipes58/cov_municipio_pop_total)*10000,
         y_qtd_equipes59  = (y_qtd_equipes59/cov_municipio_pop_total)*10000,
         y_qtd_equipes60  = (y_qtd_equipes60/cov_municipio_pop_total)*10000,
         y_qtd_equipes75  = (y_qtd_equipes75/cov_municipio_pop_total)*10000,
         y_qtd_saude_mental  = (y_saude_mental/cov_municipio_pop_total)*10000,
         
         #cobertura potencial:
         y_qt_equipes_sf = (y_qt_equipes_sf*3450)/cov_municipio_pop_total,
         y_acsimplantado = (y_acsimplantado*750)/cov_municipio_pop_total,
         y_unidades_caps = (y_unidades_caps/cov_municipio_pop_total)*10000)
         
  
```


# Função RDD
```{r}

RDD <- function(df, x, y) {
  library(rdrobust)
  library(rlang)

  # pega o nome da variável y em formato string
  y_name <- as_label(enquo(y))

  df <- df |>
    filter(
      !is.na({{x}}),
      !is.na({{y}}),
      !is.na(ano),
      # !is.na(cov_candidato_patrimonio),
      # !is.na(cov_candidato_despesa_campanha_rs),
      !is.na(cov_reeleicao),
      !is.na(cov_candidato_partido),
      !is.na(cov_candidato_educacao_agrupada),
      !is.na(cov_candidato_idade),
      !is.na(cov_municipio_proporcao_mulheres_pop),
      !is.na(cov_municipio_pop_total),
      !is.na(cd_municipio_ibge_7)
    )
  
    # se não tiver dados suficientes, pula
  if (nrow(df) < 30 || length(unique(df |> pull({{y}}))) < 5) {
    cat("\n====================\n")
    cat("Variável:", y_name, "- não tem dados suficientes. Pulando.\n")
    return(NULL)
  }


  controls <- model.matrix(
    ~ ano 
    + cov_reeleicao
    + cov_candidato_partido
    + cov_candidato_educacao_agrupada
    + cov_candidato_idade
    + cov_municipio_proporcao_mulheres_pop
    + cov_municipio_pop_total
    # + cov_candidato_patrimonio
    # + cov_candidato_despesa_campanha_rs
    ,data = df)

  x_vals <- df |> pull({{x}})
  y_vals <- df |> pull({{y}})

  regressao <- rdrobust(
    x = x_vals,
    y = y_vals,
    covs = controls,
    cluster = df$cd_municipio_ibge_7,
    all = TRUE,
    kernel = "triangular"
  )

  cat("\n====================\n")
  cat("Resultado para variável:", y_name, "\n")
  print(summary(regressao))

  h <- regressao$bws[1]

  dados_filtrados <- tibble(x = x_vals, y = y_vals) |>
    filter(abs(x) <= h)

  ymax <- mean(dados_filtrados$y)

  rdplot(
    y = y_vals,
    x = x_vals,
    kernel = "triangular",
    x.lim = c(-h, h),
    y.lim = c(0, ymax * 2),
    nbins = 100,
    p = 1,
    title = paste("RDD Plot -", y_name),
    y.label = y_name,
    x.label = as_label(enquo(x))
  )
}

```

rdd teste com filtro
```{r}
RDDt <- function(df, x, y) {

  library(rdrobust)
  
    # pega o nome da variável y em formato string
  y_name <- as_label(enquo(y))
  cat("\n====================\n")
  cat("Resultado para variável:", y_name, "\n")

  df <- df |>
    filter(
      !is.na({{x}}),
      !is.na({{y}}),
      !is.na(ano),
      !is.na(cov_reeleicao),
      !is.na(cov_candidato_partido),
      # !is.na(cov_candidato_patrimonio),
      # !is.na(cov_candidato_despesa_campanha_rs),
      !is.na(cov_candidato_educacao_agrupada),
      !is.na(cov_candidato_idade),
      !is.na(cov_municipio_proporcao_mulheres_pop),
      !is.na(cov_municipio_pop_total),
      # !is.na(cov_pib_pc),
      !is.na(cd_municipio_ibge_7)
    )

  num_eventos <- df |> summarise(total = sum({{y}}, na.rm = TRUE)) |> pull(total)

  if (num_eventos < 50) {
    message(glue::glue("Só {num_eventos} eventos. Pulando variável."))
    return(NULL)
  }
  
  
  controls <- model.matrix(
    ~ ano 
    + cov_reeleicao 
    + cov_candidato_partido 
    #+ cov_candidato_patrimonio 
    #+ cov_candidato_despesa_campanha_rs 
    + cov_candidato_educacao_agrupada 
    + cov_candidato_idade
    + cov_municipio_proporcao_mulheres_pop 
    + cov_municipio_pop_total 
    #+ cov_pib_pc
    , data = df)

  x_vals <- df |> pull({{x}})
  y_vals <- df |> pull({{y}})

  regressao <- rdrobust(
    x = x_vals,
    y = y_vals,
    covs = controls,
    cluster = df$cd_municipio_ibge_7,
    all = TRUE,
    kernel = "triangular"
  )

  print(summary(regressao))

  h <- regressao$bws[1]

  dados_filtrados <- tibble(x = x_vals, y = y_vals) |>
    filter(abs(x) <= h)

  ymax <- mean(dados_filtrados$y)

  rdplot(
    y = y_vals,
    x = x_vals,
    kernel = "triangular",
    x.lim = c(-h, h),
    y.lim = c(0, ymax * 2),
    title = paste("RDD Plot -", y_name),
    nbins = 100,
    p = 1
  )
}
```

rdd original sem filtro
```{r}


RDDo <- function(df, x, y) {

  library(rdrobust)
  
  df <- df |>
    filter(
      !is.na({{x}}),
      !is.na({{y}}),
      !is.na(ano),
      !is.na(cov_reeleicao),
      !is.na(cov_candidato_partido),
      # !is.na(cov_candidato_patrimonio),
      # !is.na(cov_candidato_despesa_campanha_rs),
      !is.na(cov_candidato_educacao_agrupada),
      !is.na(cov_candidato_idade),
      !is.na(cov_municipio_proporcao_mulheres_pop),
      !is.na(cov_municipio_pop_total),
      !is.na(cd_municipio_ibge_7)
    )

  controls <- model.matrix(
    ~ ano 
    + cov_reeleicao 
    + cov_candidato_partido 
    # + cov_candidato_patrimonio 
    # + cov_candidato_despesa_campanha_rs 
    + cov_candidato_educacao_agrupada 
    + cov_candidato_idade
    + cov_municipio_proporcao_mulheres_pop 
    + cov_municipio_pop_total
    ,data = df)

  x_vals <- df |> pull({{x}})
  y_vals <- df |> pull({{y}})

  regressao <- rdrobust(
    x = x_vals,
    y = y_vals,
    covs = controls,
    cluster = df$cd_municipio_ibge_7,
    all = TRUE,
    kernel = "triangular"
  )

  print(summary(regressao))

  h <- regressao$bws[1]

  dados_filtrados <- tibble(x = x_vals, y = y_vals) |>
    filter(abs(x) <= h)

  ymax <- mean(dados_filtrados$y)

  rdplot(
    y = y_vals,
    x = x_vals,
    kernel = "triangular",
    x.lim = c(-h, h),
    y.lim = c(0, ymax * 2),
    nbins = 100,
    p = 1
  )
}

```


#RDD
```{r}

y_vars <- names(df_rdd_adriano)[grepl("^y_", names(df_rdd_adriano))]

map(y_vars, ~ {RDD(df_rdd_adriano, x = val_margem_vitoria_feminina, y = !!sym(.x))})


```

```{r}
y_vars <- names(df_rdd_adriano)[grepl("^y_", names(df_rdd_adriano))]

map(y_vars, ~ {RDDo(df_rdd_adriano, x = val_margem_vitoria_feminina, y = !!sym(.x))})
```

```{r}

RDD(df_rdd_adriano, x = val_margem_vitoria_feminina, y = y_acsimplantado)

rdplot(
  y = df_rdd_adriano$y_acsimplantado,
  x = df_rdd_adriano$val_margem_vitoria_feminina,
  kernel = "triangular",
  x.lim = c(-0.141, 0.141),
  y.lim = c(0.03, 0.4),
  nbins = 100,
  p = 1)

```




