---
title: "close-election"
output: html_document
date: "2025-08-27"
---

```{r}
library(tidyverse)

```


```{r}
df_candidates <- readRDS('../../dados/TSE/TSE_tratado_completo.RDS')
df_datasus <- readRDS('../../dados/Datasus/SIMSUS/var_dependentes_simsus.RDS')

## Duda
df_candidates <- readRDS('../../dados/TSE_tratado_completo.RDS')
df_datasus <- readRDS('../../dados/Bases/var_dependentes_simsus.RDS')
```


```{r}

df_datasus |> 
  filter(idade >= 15 & idade <= 49, cd_sexo == 2) |> 
  group_by(mandato, cd_muni_res, ano_obito) |>
  summarise(across(starts_with("y_"), sum, .names = "{.col}"), .groups = "drop") |>
  mutate(t = v - mandato) |>                  # distância em anos desde o início
  filter(t %in% 1:4) |>                         # só anos do mandato
  pivot_wider(
    id_cols = c(cd_muni_res, mandato),          # queremos 1 linha por muni/mandato
    names_from = t,                             # gera t1, t2, t3, t4
    values_from = starts_with("y_"), 
    names_glue = "{.value}_t{t}"
  )


```



```{r}

df_simsus_dependentes <- df_datasus |> 
  filter(idade >= 15 & idade <= 49, cd_sexo == 2)  |> 
  group_by(mandato, cd_muni_res) |>
  summarise(across(
  .cols = starts_with("y_"),       
  .fns = ~ sum(.),  
  .names = "{.col}"              
  )) |> 
  ungroup() |> 
  arrange(cd_muni_res, mandato) |> 
  group_by(cd_muni_res) |> 
  mutate(across(
    .cols = starts_with("y_"),       
    .fns = ~ lag(.),  
    .names = "{.col}_previous"))
  

```
## Com variável death of despair - Duda
```{r}
df_simsus_dependentes <- df_datasus |> 
  filter(idade >= 15 & idade <= 49, cd_sexo == 2) |> 

  group_by(mandato, cd_muni_res) |>
  summarise(
    across(
      .cols = starts_with("y_"),
      .fns  = ~ sum(.),
      .names = "{.col}"
    ),
    .groups = "drop"
  ) |> 

  arrange(cd_muni_res, mandato) |> 
  group_by(cd_muni_res) |> 

  mutate(
    across(
      .cols = starts_with("y_"),
      .fns  = ~ lag(.),
      .names = "{.col}_previous"
    ),
    
    # nova variável SOMA do mandato atual
    y_death_despair = y_suicide + y_overdose + y_alcoholic_disease,

    # nova variável SOMA do mandato anterior
    y_death_despair_previous = y_suicide_previous + y_overdose_previous + y_alcoholic_disease_previous
  ) |> 

  ungroup()

```

```{r}
df_rdd_simsus <- df_candidates |> 
  left_join(df_simsus_dependentes, by= c('ano' = 'mandato', 'cd_municipio_ibge_6' = 'cd_muni_res')) |> 
  mutate(
    across(starts_with('y_'), ~ (./cov_municipio_pop_total)*100000),
    across(starts_with('y_'), ~ replace_na(., 0)),
  ) |> 
  filter(!ano %in% c(2004, 2020))
  
df_rdd_simsus |> select(-y_overdose, -y_suicide ,-y_alcoholic_disease)

```


```{r}

RDD <- function(df, x, y) {

  library(rdrobust)
  
  df <- df |>
    filter(
      !is.na({{x}}),
      !is.na({{y}}),
      !is.na(ano),
      # !is.na(cov_reeleicao),
      # !is.na(cov_candidato_partido),
      #!is.na(cov_candidato_patrimonio),
      #!is.na(cov_candidato_despesa_campanha_rs),
      # !is.na(cov_candidato_educacao_agrupada),
      # !is.na(cov_candidato_idade),
      # !is.na(cov_municipio_proporcao_mulheres_pop),
      # !is.na(cov_municipio_pop_total),
      !is.na(cd_municipio_ibge_7)
    )

  controls <- model.matrix(
    ~ ano 
    # + cov_reeleicao
    # + cov_candidato_partido
    #+ cov_candidato_patrimonio
    #+ cov_candidato_despesa_campanha_rs
    # + cov_candidato_educacao_agrupada
    # + cov_candidato_idade
    # + cov_municipio_proporcao_mulheres_pop
    # + cov_municipio_pop_total
    , data = df)

  x_vals <- df |> pull({{x}})
  y_vals <- df |> pull({{y}})

  regressao <- rdrobust(
    x = x_vals,
    y = y_vals,
    covs = controls,
    cluster = df$cd_municipio_ibge_7,
    all = TRUE,
    kernel = "triangular"
  )

  print(summary(regressao))

  h <- regressao$bws[1]

  dados_filtrados <- tibble(x = x_vals, y = y_vals) |>
    filter(abs(x) <= h)

  ymax <- mean(dados_filtrados$y)

  rdplot(
    y = y_vals,
    x = x_vals,
    kernel = "triangular",
    x.lim = c(-h, h),
    y.lim = c(0, ymax * 2),
    nbins = 100,
    p = 1
  )
}

```

##Função rdd pra dados na
```{r}
RDDT <- function(df, x, y) {

  library(rdrobust)
  
    # pega o nome da variável y em formato string
  y_name <- as_label(enquo(y))
  cat("\n====================\n")
  cat("Resultado para variável:", y_name, "\n")

  df <- df |>
    filter(
      !is.na({{x}}),
      !is.na({{y}}),
      !is.na(ano),
      !is.na(cov_reeleicao),
      !is.na(cov_candidato_partido),
      # !is.na(cov_candidato_patrimonio),
      # !is.na(cov_candidato_despesa_campanha_rs),
      !is.na(cov_candidato_educacao_agrupada),
      !is.na(cov_candidato_idade),
      !is.na(cov_municipio_proporcao_mulheres_pop),
      !is.na(cov_municipio_pop_total),
      # !is.na(cov_pib_pc),
      !is.na(cd_municipio_ibge_7)
    )

  num_eventos <- df |> summarise(total = sum({{y}}, na.rm = TRUE)) |> pull(total)

  if (num_eventos < 50) {
    message(glue::glue("Só {num_eventos} eventos. Pulando variável."))
    return(NULL)
  }
  
  
  controls <- model.matrix(
    ~ ano 
    + cov_reeleicao 
    + cov_candidato_partido 
    #+ cov_candidato_patrimonio 
    #+ cov_candidato_despesa_campanha_rs 
    + cov_candidato_educacao_agrupada 
    + cov_candidato_idade
    + cov_municipio_proporcao_mulheres_pop 
    + cov_municipio_pop_total 
    #+ cov_pib_pc
    , data = df)

  x_vals <- df |> pull({{x}})
  y_vals <- df |> pull({{y}})

  regressao <- rdrobust(
    x = x_vals,
    y = y_vals,
    covs = controls,
    cluster = df$cd_municipio_ibge_7,
    all = TRUE,
    kernel = "triangular"
  )

  print(summary(regressao))

  h <- regressao$bws[1]

  dados_filtrados <- tibble(x = x_vals, y = y_vals) |>
    filter(abs(x) <= h)

  ymax <- mean(dados_filtrados$y)

  rdplot(
    y = y_vals,
    x = x_vals,
    kernel = "triangular",
    x.lim = c(-h, h),
    y.lim = c(0, ymax * 2),
    title = paste("RDD Plot -", y_name),
    nbins = 100,
    p = 1
  )
}

```

# homicidio de mulheres - 15 ~ 49 - ambiente doméstico
```{r}


df_rdd_simsus |> RDD(val_margem_vitoria_feminina, y_alcoholic_disease)

```
# Suicídio

```{r}

df_rdd_simsus |> RDD(val_margem_vitoria_feminina, y_suicide)

```

## RDD simsus-Duda
```{r}

y_vars <- names(df_rdd_simsus)[grepl("^y_", names(df_rdd_simsus))]

map(y_vars, ~ {RDD(df_rdd_simsus, x = val_margem_vitoria_feminina, y = !!sym(.x))})

#####rdd 2020
#map(y_vars, ~ {Rdd20(df_rdd_sinan, x = val_margem_vitoria_feminina, y = !!sym(.x))})

```

 


```{r}

library(tidyverse)
library(rdrobust)
library(rlang)
library(glue)
library(patchwork)



RDD_sensibilidade <- function(df, x, y) {

  x <- enquo(x)
  y <- enquo(y)
  y_name <- as_label(y)

  cat("\n====================\n")
  cat("Variável dependente:", y_name, "\n")

  df <- df |>
    filter(!is.na(!!x), !is.na(!!y), !is.na(ano), !is.na(cd_municipio_ibge_7))

  num_eventos <- df |> summarise(total = sum(!!y, na.rm = TRUE)) |> pull()
  if (num_eventos < 50) {
    message(glue("Só {num_eventos} eventos. Pulando variável: {y_name}"))
    return(NULL)
  }

  controls <- model.matrix(~ ano, data = df)

  x_vals <- df |> pull(!!x)
  y_vals <- df |> pull(!!y)

  # Roda com bandwidth ótimo
  rd_opt <- rdrobust(
    x = x_vals,
    y = y_vals,
    covs = controls,
    cluster = df$cd_municipio_ibge_7,
    all = TRUE,
    kernel = "triangular"
  )
  print(summary(rd_opt))

  # Sensibilidade
  bandwidths <- seq(0.05, 1, by = 0.05)
  betas <- numeric(length(bandwidths))
  pvalues <- numeric(length(bandwidths))

  for (i in seq_along(bandwidths)) {
    res <- rdrobust(
      x = x_vals, y = y_vals,
      covs = controls,
      cluster = df$cd_municipio_ibge_7,
      h = bandwidths[i],
      all = TRUE,
      kernel = "triangular"
    )
    betas[i] <- res$coef[1]
    pvalues[i] <- res$pv[1]
  }

  results <- tibble(
    bandwidth = bandwidths,
    beta = betas,
    pvalue = pvalues
  )

  g1 <- results |>
    ggplot(aes(bandwidth, beta)) +
    geom_line() + geom_point() +
    labs(title = paste("Coef vs bandwidth -", y_name), y = "coef.")

  g2 <- results |>
    ggplot(aes(bandwidth, pvalue)) +
    geom_line() + geom_point() +
    labs(title = paste("p-value vs bandwidth -", y_name), y = "p-value")

  g1 / g2
}
```

```{r}
y_vars <- names(df_rdd_simsus)[grepl("^y_", names(df_rdd_simsus))]

map(
  y_vars,
  ~ RDD_sensibilidade(
      df = df_rdd_simsus,
      x = val_margem_vitoria_feminina,
      y = !!sym(.x)
    )
)

```




