---
title: "rdd_covs"
output: html_document
date: "2025-11-13"
---

```{r}
library(tidyverse)
library(rdrobust)
library(fastDummies)
```


```{r}
df_candidates <- readRDS('../dados/TSE/TSE_tratado_completo.RDS')
df_candidates

```


```{r}
df_cov <- df_candidates |>
  dummy_cols( c('cov_candidato_partido', 'cov_candidato_educacao_agrupada'), 
    remove_first_dummy = TRUE,
    remove_selected_columns = TRUE) |> 
  select(-cov_reeleicao, -cd_municipio_ibge_6, -cd_municipio_tse) |> 
  select(ano, val_margem_vitoria_feminina, cov_candidato_idade, cov_candidato_patrimonio, cov_candidato_despesa_campanha_rs,
         cov_municipio_pop_total, cov_municipio_proporcao_mulheres_pop,
         cov_candidato_partido_DEM, cov_candidato_partido_PMDB, cov_candidato_partido_PSDB, cov_candidato_partido_PT,
         'cov_candidato_educacao_agrupada_Incomplete Elementary', 'cov_candidato_educacao_agrupada_Incomplete High School',
         'cov_candidato_educacao_agrupada_Incomplete University', 'cov_candidato_educacao_agrupada_Complete High School', 'cov_candidato_educacao_agrupada_Complete University') |> 
  
  mutate(genero = ifelse(val_margem_vitoria_feminina < 0,  "male", "female")) 


compute_stats <- function(data, var){
  var_sym <- rlang::sym(var)   # converte string para símbolo
  
  female <- data |> filter(genero=="female") |> pull(!!var_sym)
  male   <- data |> filter(genero=="male")   |> pull(!!var_sym)
  
  tibble(
    variable = var,   # agora já é string, perfeito
    female_mean = mean(female, na.rm=TRUE),
    female_n = sum(!is.na(female)),
    male_mean = mean(male, na.rm=TRUE),
    male_n = sum(!is.na(male)),
    p_value = t.test(female, male)$p.value
  )
}




vars <- c(
  "cov_candidato_idade",
  "cov_candidato_patrimonio",
  "cov_candidato_despesa_campanha_rs",
  "cov_municipio_pop_total",
  "cov_municipio_proporcao_mulheres_pop",
  "cov_candidato_partido_DEM",
  "cov_candidato_partido_PMDB",
  "cov_candidato_partido_PSDB",
  "cov_candidato_partido_PT",
  "cov_candidato_educacao_agrupada_Incomplete Elementary",
  "cov_candidato_educacao_agrupada_Incomplete High School",
  "cov_candidato_educacao_agrupada_Incomplete University",
  "cov_candidato_educacao_agrupada_Complete High School",
  "cov_candidato_educacao_agrupada_Complete University"
)

table_cov <- purrr::map_dfr(vars, ~compute_stats(df_cov, .x)) |> 
  mutate(
    p_value_clean = ifelse(p_value < 0.001,
                           "<0.001",
                           sprintf("%.3f", p_value))
  )


```


```{r}

names(df_cov)[
  grepl("^cov_", names(df_cov)) &
    !names(df_cov) %in% c(
      "cov_candidato_partido",
      "cov_candidato_educacao_agrupada"
    )
]

```

```{r}

RDD <- function(df, x, y) {

  library(rdrobust)
  
    # pega o nome da variável y em formato string
  y_name <- as_label(enquo(y))
  cat("\n====================\n")
  cat("Resultado para variável:", y_name, "\n")

  df <- df |>
    filter(
      !is.na({{x}}),
      !is.na({{y}}),
    )

  num_eventos <- df |> summarise(total = sum({{y}}, na.rm = TRUE)) |> pull(total)

  if (num_eventos < 10) {
    message(glue::glue("Só {num_eventos} eventos. Pulando variável."))
    return(NULL)
  }
  
  x_vals <- df |> pull({{x}})
  y_vals <- df |> pull({{y}})

  regressao <- rdrobust(
    x = x_vals,
    y = y_vals,
    cluster = df$cd_municipio_ibge_7,
    all = TRUE,
    kernel = "triangular"
  )

  print(summary(regressao))

  h <- regressao$bws[1]

  dados_filtrados <- tibble(x = x_vals, y = y_vals) |>
    filter(abs(x) <= h)

  ymax <- mean(dados_filtrados$y)

  rdplot(
    y = y_vals,
    x = x_vals,
    kernel = "triangular",
    x.lim = c(-h, h),
    y.lim = c(0, ymax * 2),
    title = paste("RDD Plot -", y_name),
    nbins = 100,
    p = 1
  )
}


```

```{r}

y_vars <- names(df_cov)[grepl("^cov_", names(df_cov))]

map(
  y_vars,
  ~ RDD(
      df = df_cov,
      x = val_margem_vitoria_feminina,
      y = !!sym(.x)
    )
)

```

```{r}

df_cov %>%
  summarise(across(
    everything(),
    list(
      mean = ~mean(.x, na.rm = TRUE),
      sd = ~sd(.x, na.rm = TRUE),
      min = ~min(.x, na.rm = TRUE),
      p25 = ~quantile(.x, 0.25, na.rm = TRUE),
      median = ~median(.x, na.rm = TRUE),
      p75 = ~quantile(.x, 0.75, na.rm = TRUE),
      max = ~max(.x, na.rm = TRUE)
    ),
    .names = "{.col}_{.fn}"
  ))

```

```{r}

install.packages('skimr')

skimr::skim(df_cov)


```
























