---
title: "mortes-ocultas"
author: "Vandrade"
date: "2025-03-28"
output: html_document
---

```{r}
library(tidyverse)

```


```{r}

datasus_raw <- readRDS("datasus_raw.rds")

```


Mortes Violentas com Causa Indeterminada (MVCI)

```{r}

df_datasus <- datasus_raw |>
  
  mutate(cd_causa_basica = substr(CAUSABAS, 1, 3),
         y_mvci = ifelse(cd_causa_basica >= "Y10" & cd_causa_basica <= "Y34", TRUE, FALSE),
         y_homicide = ifelse(cd_causa_basica >= "X85" & cd_causa_basica <= "Y09", TRUE, FALSE),
         y_domestic_homicide = ifelse(cd_causa_basica >= "X85" & cd_causa_basica <= "Y09" & LOCOCOR == "3" , TRUE, FALSE),
         
         y_accident_and_suicide= ifelse(cd_causa_basica >= "V01" & cd_causa_basica <= "V99" |
                                          cd_causa_basica >= "W32" & cd_causa_basica <= "W34" |
                                          cd_causa_basica >= "W25" & cd_causa_basica <= "W26" |
                                          cd_causa_basica >= "W00" & cd_causa_basica <= "W19" |
                                          cd_causa_basica >= "W20" & cd_causa_basica <= "W24" |
                                          cd_causa_basica >= "W27" & cd_causa_basica <= "W31" |
                                          cd_causa_basica >= "W35" & cd_causa_basica <= "W43" |
                                          
                                          cd_causa_basica == "W49" |
                                          cd_causa_basica == "W51" |
                                          cd_causa_basica == "W50" |
                                          
                                          cd_causa_basica >= "W65" & cd_causa_basica <= "W74" |
                                          cd_causa_basica >= "W75" & cd_causa_basica <= "W76" |

                                          cd_causa_basica >= "X00" & cd_causa_basica <= "X09" |
                                          cd_causa_basica >= "X40" & cd_causa_basica <= "X49" |
                                          cd_causa_basica >= "X58" & cd_causa_basica <= "X59" | # acidentes
                                          
                                          cd_causa_basica >= "X60" & cd_causa_basica <= "X69" |
                                          cd_causa_basica == "X70" |
                                          cd_causa_basica == "X71" |
                                          cd_causa_basica >= "X72" & cd_causa_basica <= "X79" |
                                          cd_causa_basica >= "X80" & cd_causa_basica <= "X84" |
                                          cd_causa_basica >= "X60" & cd_causa_basica <= "X69", TRUE, FALSE), # agressoes
                                          
         
         y_suicide = ifelse(cd_causa_basica >= "X60" & cd_causa_basica <= "X69" |
                              cd_causa_basica == "X70" | 
                              cd_causa_basica == "X71" |
                              cd_causa_basica >= "X72" & cd_causa_basica <= "X79" | 
                              cd_causa_basica >= "X80" & cd_causa_basica <= "X84" |
                              cd_causa_basica >= "X60" & cd_causa_basica <= "X69", TRUE, FALSE), 
         
         dt_obito = as.Date(DTOBITO, format="%d%m%Y"),
         ano_obito = as.factor(year(dt_obito)),
         
         death_type = case_when(y_mvci == TRUE ~ 'MVCI',
                                y_domestic_homicide == TRUE ~ 'Domestic Homicide',
                                y_homicide == TRUE ~ 'Homicide', 
                                y_suicide == TRUE ~ 'Suicide',
                                y_accident_and_suicide == TRUE ~ "Accident or Suicide",
                                
                                .default = 'others'))

```

```{r}

df_datasus |>
  
  filter(!death_type %in% c('others', 'Domestic Homicide', 'Accident or Suicide'), 
         SEXO == 2) |> 

  
  ggplot(aes(x = ano_obito, fill = death_type)) +
  geom_bar(position = "fill") + 
  theme_minimal() +
  coord_flip() + 
  scale_fill_brewer(palette = "Reds")
```


```{r}

df_datasus |> 
  group_by(ano_obito, death_type) |> 
  
  summarize(amount = n(), .groups = "drop") |> 
  
  group_by(ano_obito) |> 
  
  mutate(fraction = (amount/sum(amount)) * 100) |> 
  
  filter(death_type == 'MVCI') |> 
  
  
  ggplot(aes(x = ano_obito, fill = death_type)) + 
  geom_bar(position = "stack") + 
  theme_minimal() +
  coord_flip()



```







