---
title: "TSE-Margin-Victory"
author: "Vandrade"
date: "2024-06-10"
output: html_document
---

# Library and Setup

```{r warning=F}

library(tidyverse)
library(electionsBR)

year = c(2004, 2008, 2012, 2016, 2020)

```

# ElectionsBR 

## Electoral Zones Data
```{r}

fun_vote_mun_zone <- function(year) {
  elections_tse(year, type = 'vote_mun_zone', uf = 'all') |> 
    mutate(CD_MUNICIPIO = as.factor(CD_MUNICIPIO))}

df_candidates_votes <- map_df(year, fun_vote_mun_zone) |> 
  mutate(votos_zona = coalesce(QT_VOTOS_NOMINAIS_VALIDOS, QT_VOTOS_NOMINAIS)) |> 
  select(ano = ANO_ELEICAO,
         estado = SG_UF,
         cd_municipio_tse = CD_MUNICIPIO,
         nm_municipio = NM_MUNICIPIO,
         zona = NR_ZONA,
         cargo = DS_CARGO,
         nr_candidato = NR_CANDIDATO,
         nm_candidato = NM_CANDIDATO,
         votos_zona,
         partido = SG_PARTIDO) |> 
  filter(cargo == 'Prefeito') |> 
  group_by(ano, estado, cd_municipio_tse, nr_candidato) |> 
  summarize(nm_municipio = first(nm_municipio),
            nm_candidato = first(nm_candidato), 
            total_votos = sum(votos_zona),
            partido = first(partido)) |> 
  group_by(ano, estado, cd_municipio_tse) |> 
  mutate(resultado = ifelse(total_votos == max(total_votos), 'Eleito', 'Não Eleito')) |> 
  mutate(cd_municipio_tse = as.factor(cd_municipio_tse)) |> 
  ungroup()
 
```

## Details about Electoral Zones (most importantly: Electoral Population)
```{r}

fun_details_mun_zone <- function(year) {
  elections_tse(year, type = 'details_mun_zone', uf = 'all') |> 
    mutate(CD_MUNICIPIO = as.factor(CD_MUNICIPIO))}

df_pop_votante <- map_df(year, fun_details_mun_zone) |> 
    select(ano = ANO_ELEICAO,
         estado = SG_UF,
         cd_municipio_tse = CD_MUNICIPIO,
         nm_municipio = NM_MUNICIPIO,
         zona = NR_ZONA,
         cargo = DS_CARGO,
         pop_votante = QT_APTOS,
         nr_abstencoes = QT_ABSTENCOES) |> 
  filter(cargo == 'Prefeito') |> 
  group_by(ano, estado, cd_municipio_tse) |> 
  summarize(nm_municipio = first(nm_municipio),
            pop_votante = sum(pop_votante)) |> 
  mutate(cd_municipio_tse = as.factor(cd_municipio_tse)) |> 
  ungroup()

```

## Details about Candidates

```{r}

fun_details_mun_zone <- function(year) {
  df <- elections_tse(year, type = 'candidate', uf = 'all')
  if (year != 2020) {
    df$NR_PROTOCOLO_CANDIDATURA <- as.character(df$NR_PROTOCOLO_CANDIDATURA)
  }
  df$NR_CPF_CANDIDATO <- as.character(df$NR_CPF_CANDIDATO)
  df$CD_COR_RACA <- as.character(df$CD_COR_RACA)

  return(df)
}


df_candidates_details_raw <- map_df(year, fun_details_mun_zone) 

  
df_candidates_details <- df_candidates_details_raw |> 
  select(ano = ANO_ELEICAO, #selecionando e filtrando as variaveis
         estado = SG_UF,
         cd_municipio_tse = SG_UE,
         nm_municipio_tse = NM_UE,
         cargo = DS_CARGO,
         nr_candidato = NR_CANDIDATO,
         nm_candidato = NM_CANDIDATO,
         partido = SG_PARTIDO,
         idade = NR_IDADE_DATA_POSSE,
         genero = DS_GENERO,
         educacao = DS_GRAU_INSTRUCAO,
         cor_raca = DS_COR_RACA,
         ocupacao = DS_OCUPACAO,
         cd_seq_candidato =SQ_CANDIDATO) |> 
  filter(cargo == 'PREFEITO') |> 
  group_by(ano, estado, cd_municipio_tse, nr_candidato) |> # some of the candidates are repeated. 
  summarise(idade = max(idade),
            nm_partido = first(partido), 
            nm_candidato = first(nm_candidato),
            nm_genero = first(genero),
            nm_educacao = first(educacao),
            nm_cor_raca = first(cor_raca),
            nm_ocupacao = first(ocupacao),
            nm_municipio_tse = first(nm_municipio_tse),
            cd_seq_candidato = first(cd_seq_candidato)) |> 
  ungroup() |> 
  mutate(cd_municipio_tse = as.factor(cd_municipio_tse)) 

 
df_candidates_details_raw |> count(ANO_ELEICAO, SG_UE, NR_CANDIDATO) |> arrange(desc(n))

df_candidates_details_raw |> filter(ANO_ELEICAO == 2020,
                                    SG_UE == '58440', 
                                    NR_CANDIDATO == '14',
                                    DS_CARGO == 'PREFEITO') 

```
```{r}

df |>
  mutate(VR_BEM_CANDIDATO = str_replace(VR_BEM_CANDIDATO,pattern = ',', replacement = '.'),
         VR_BEM_CANDIDATO = as.numeric(VR_BEM_CANDIDATO)) |>
  filter(SG_UE == '58440',
             SQ_CANDIDATO %in% c('190001415011', '190001336348', '190001507051', '190001244496')) |> 
  group_by(SQ_CANDIDATO) |> 
  summarise(valor_total_bens = sum(VR_BEM_CANDIDATO, na.rm = TRUE)) 
  
```

## Value of Assets

```{r}
year = c(2008, 2012, 2016, 2020)


fun_values_of_assets <- function(year) {
  df <- elections_tse(year, type = 'personal_finances', uf = 'all')

  df <- df |> 
    select(ANO_ELEICAO,
           SG_UE,
           SQ_CANDIDATO,
           DS_BEM_CANDIDATO,
           VR_BEM_CANDIDATO)
  
  return(df)
}

df_values_of_assets <- map_df(year, fun_values_of_assets) |> 
  
  select(ano = ANO_ELEICAO,
         cd_municipio_tse = SG_UE,
         cd_seq_candidato = SQ_CANDIDATO,
         nm_desc_bem = DS_BEM_CANDIDATO,
         val_patrimonio_candidato = VR_BEM_CANDIDATO) |> 
  mutate(val_patrimonio_candidato = str_replace(val_patrimonio_candidato,pattern = ',', replacement = '.'),
         val_patrimonio_candidato = as.numeric(val_patrimonio_candidato)) |>

  group_by(ano, cd_municipio_tse, cd_seq_candidato) |> 
  summarise(val_patrimonio_candidato = sum(val_patrimonio_candidato))
  

```

# Joining databases 
```{r}
df_candidates_votes |> head(1)
```

```{r}
df_candidates_details |> 
  count(ano, cd_municipio_tse, nr_candidato) |> 
  arrange(desc(n))
```

```{r}

df_tse_completo_raw <- df_candidates_votes |> 
  select(-estado, -nm_candidato, -nm_municipio) |> 
  left_join(df_candidates_details, by = c('ano', 'cd_municipio_tse', 'nr_candidato')) |> 
  left_join(df_values_of_assets, by = c('ano', 'cd_municipio_tse', 'cd_seq_candidato')) |>
  select(-estado) |> 
  left_join(df_pop_votante, by = c('ano', 'cd_municipio_tse')) |> 
  mutate(nr_candidato = as.factor(nr_candidato))



```


# adicionando covariadas

```{r}

df_gastos_de_campanha <- readRDS('../dados/dados-output/covariadas/TSE-Gasto-de-Campanha.RDS') |> 
  mutate(ano = as.numeric(ano))

dicionario_tse_ibge <- read.csv('../dados/dicionario-muni-TSE-Ibge/municipios_brasileiros_tse.csv') |> 
  select(cd_municipio_tse = codigo_tse,
         cd_municipio_ibge_7  = codigo_ibge) |> 
  mutate(cd_municipio_tse = as.factor(cd_municipio_tse),
         cd_municipio_ibge_6 = substr(cd_municipio_ibge_7, 1, 6))

df_pop_masc <- read.csv('../dados/covariadas-IBGE/pop_masc_fem/ibge_cnv_popbr182320189_100_70_198.csv', sep = ';', skip = 4, encoding = 'latin1') |> 
  select(municipio = Município, val_pop_masculina = População_residente) |> 
  mutate(cd_municipio_ibge_6 = as.factor(substr(municipio, 1, 6)),
         val_pop_masculina = as.numeric(val_pop_masculina)) |> 
  filter(is.na(val_pop_masculina) == FALSE) |> 
  select(-municipio)

df_pop_genders <- read.csv('../dados/covariadas-IBGE/pop_masc_fem/ibge_cnv_popbr220607189_100_70_198.csv', sep = ';', skip = 4, encoding = 'latin1') |> 
  select(municipio = Município, val_pop_feminina = População_residente) |> 
  mutate(cd_municipio_ibge_6 = as.factor(substr(municipio, 1, 6)),
         val_pop_feminina = as.numeric(val_pop_feminina)) |> 
  filter(is.na(val_pop_feminina) == FALSE) |> 
  select(-municipio) |> 
  
  left_join(df_pop_masc, by = c('cd_municipio_ibge_6'))



df_tse_completo_raw |> mutate(cd_municipio_tse = as.factor(as.numeric(cd_municipio_tse))) |>
  left_join(dicionario_tse_ibge, by = c('cd_municipio_tse')) |> 
  left_join(df_gastos_de_campanha, by = c('ano', 'cd_municipio_tse' = 'cd_tse_mun','nr_candidato' = 'cd_num_candidato', 'nm_candidato')) |> 
  left_join(df_pop_genders, by = c('cd_municipio_ibge_6')) |> 
  mutate(val_pop_total = val_pop_feminina + val_pop_masculina) |> 
  write_rds('../dados/dados-output/TSE-Completo.RDS')



```


## creating RDS file 
```{r}

saveRDS(candidates, file = "Dados/candidates.rds")

```













